[package]
name = "torygg"
version = "0.1.0"
authors = ["nukeythenuke <nukeythenuke@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
torygg-vdf = { git = "https://github.com/nukeythenuke/torygg-vdf" }

clap = "2"
dirs = "4"
log = "0.4"
simplelog = "0.12"
tempfile = "3"
walkdir = "2"

#esplugin = "3.2.0"
