[workspace]
members = ["torygg", "torygg-cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Norman McKeown <normanmckeown@duck.com>"]
edition = "2021"
license = "MIT"

[lints.clippy]
pedantic = "warn"
unreadable_literal = "allow"